### PR TITLE
iterate through relations if paginated 

### PR DESCRIPTION
**Pull request by ola-t**
This PR allows returning link to relationship as an iterator. replace #10 

see https://github.com/qvantel/jsonapi-client/issues/6

### CODE REVIEW

**Comment by ola-t** [comment]
> Would you think it possible to change this to be a new feature? I mean by adding for example a key word parameter to Session such as "return_link_relationship_as_iterator" and defaulting to False. Then add if-else to this LinkRelationship class accordingly. This would ensure backward compatibility. What do you think?

@ajjn does this work now for you?

**Comment by ajjn** [comment]
Yeah, that's great! Thanks for your contributions!

**Comment by ola-t** [comment]
When this patch could be released, roughtly?

**Comment by ola-t** [comment]
I didnt expect merging that so quickly, would you consider better name for `return_link_relationship_as_iterator` like `rel_iterator` ?

**Pull request merged**
